spring:
  application:
    name: zycloud-provider
  profiles:
    include: druid #引入数据源application-druid.yml文件
    active:
    - dev
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
---
server:
  port: 8002
spring:
  profiles: provider8002 
  
eureka:
  client:  #将客户端注册到微服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: zycloud-config-provider8002 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址
---
server:
  port: 8001
spring:
  profiles: provider8001 
  
eureka:
  client:  #将客户端注册到微服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: zycloud-config-provider8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址
